# Generated by Django 5.1.4 on 2024-12-19 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_related_posts_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag_In_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='CommentReaction',
            new_name='Comment_Reaction',
        ),
        migrations.RenameModel(
            old_name='PostReaction',
            new_name='Post_Reaction',
        ),
        migrations.AddField(
            model_name='comment',
            name='users_reactions',
            field=models.ManyToManyField(related_name='comment_users_reactions', through='posts.Comment_Reaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='users_reactions',
            field=models.ManyToManyField(related_name='post_users_reactions', through='posts.Post_Reaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='responded_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='comment_reaction',
            constraint=models.UniqueConstraint(models.F('comment'), models.F('user'), name='unique_comment_user'),
        ),
        migrations.AlterModelTable(
            name='post_reaction',
            table='post_reaction',
        ),
        migrations.AddField(
            model_name='tag_in_post',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='tag_in_post',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='posts.Tag_In_Post', to='posts.tag'),
        ),
        migrations.AddConstraint(
            model_name='tag_in_post',
            constraint=models.UniqueConstraint(models.F('post'), models.F('tag'), name='unique_tag_in_post'),
        ),
    ]
